site_name: Recipe Compete App Docs
theme:
  name: material

docs_dir: src

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
